import { Colors, FontSize, Radius, Shadows, Spacing } from '@/constants/theme';
import { StyleSheet } from 'react-native';

const ASSIGNMENT_LABEL_WIDTH = 66;

export const s = StyleSheet.create({
  card: {
    backgroundColor: Colors.light.card,
    borderRadius: Radius.l,
    padding: Spacing.m,
    marginBottom: Spacing.m,
    ...Shadows.md,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.m,
  },
  orderId: { fontSize: FontSize.l, fontWeight: '700', color: Colors.light.text },
  date: { fontSize: FontSize.s, color: Colors.light.textLight },
  statusBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.m,
  },
  statusText: { fontSize: FontSize.s, fontWeight: '700' },
  customerInfo: { marginBottom: Spacing.s },
  customerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.light.background,
    padding: 10,
    borderRadius: Radius.m,
    marginBottom: Spacing.s,
  },
  customerInfoContainer: { marginLeft: Spacing.s, flex: 1 },
  customerName: { fontSize: FontSize.m, fontWeight: '600', color: Colors.light.text },
  customerPhone: { fontSize: FontSize.s, color: Colors.light.textSecondary, marginTop: 2 },
  courierClientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  courierClientName: { flex: 1, fontSize: FontSize.m, fontWeight: '600', color: Colors.light.text },
  iconButton: { padding: 4 },
  phone: {
    fontSize: FontSize.s,
    color: Colors.light.textSecondary,
    marginBottom: Spacing.s,
    marginLeft: 22,
  },
  addressBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: Spacing.s,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: Colors.light.background,
    borderRadius: Radius.m,
    padding: Spacing.sm,
    marginBottom: Spacing.s,
  },
  addressText: {
    flex: 1,
    fontSize: FontSize.m,
    color: Colors.light.textSecondary,
    marginLeft: 6,
    lineHeight: 18,
  },
  commentBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: Colors.light.warningLight,
    borderRadius: Radius.m,
    padding: Spacing.sm,
    marginBottom: Spacing.m,
    gap: 6,
  },
  commentText: { flex: 1, fontSize: FontSize.m, color: Colors.light.warningText, lineHeight: 18 },
  assignmentSection: {
    backgroundColor: Colors.light.background,
    borderRadius: Radius.m,
    padding: Spacing.sm,
    marginBottom: Spacing.m,
    gap: Spacing.xs,
  },
  assignmentRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  assignmentLabel: {
    fontSize: FontSize.s,
    color: Colors.light.textSecondary,
    width: ASSIGNMENT_LABEL_WIDTH,
  },
  assignmentName: { flex: 1, fontSize: FontSize.s, fontWeight: '600', color: Colors.light.text },
  itemsContainer: {
    backgroundColor: Colors.light.background,
    borderRadius: Radius.m,
    padding: Spacing.m,
    marginBottom: Spacing.s,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Spacing.xs,
  },
  itemName: { flex: 1, fontSize: FontSize.m, color: Colors.light.text, paddingRight: Spacing.s },
  itemQty: { fontSize: FontSize.m, fontWeight: '700', color: Colors.light.textSecondary, marginRight: Spacing.s },
  itemPrice: { fontSize: FontSize.m, fontWeight: '700', color: Colors.light.text },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.s,
    marginBottom: Spacing.s,
    backgroundColor: Colors.light.primaryLight,
    borderRadius: Radius.m,
  },
  expandButtonText: {
    color: Colors.light.primary,
    fontSize: FontSize.m,
    fontWeight: '600',
    marginRight: Spacing.xs,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.light.borderLight,
    paddingTop: Spacing.s,
    marginBottom: Spacing.m,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.light.borderLight,
    paddingTop: Spacing.s,
    marginBottom: Spacing.m,
  },
  summary: { fontSize: FontSize.m, color: Colors.light.textSecondary },
  price: { fontSize: FontSize.xl, fontWeight: '800', color: Colors.light.text },
  totalAmount: { fontSize: FontSize.l, fontWeight: '800', color: Colors.light.text },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.m,
  },
  actionButtonText: { fontSize: FontSize.m, fontWeight: '700', color: Colors.light.white },
  actionButtonDisabled: { opacity: 0.6 },
  takeButton: { fontSize: 12, color: Colors.light.primary, fontWeight: '700' as const },
  addressNoMarginLeft: { marginLeft: 0 },
  dateRight: { marginBottom: 12, textAlign: 'right' as const },
});
