import { Colors, Radius, Shadows, Spacing } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  card: {
    backgroundColor: Colors.light.card,
    borderRadius: Radius.l,
    padding: Spacing.m,
    marginBottom: Spacing.m,
    ...Shadows.md,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.m,
  },
  orderId: { fontSize: 16, fontWeight: "700", color: Colors.light.text },
  statusBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: Radius.m,
  },
  statusText: { fontSize: 12, fontWeight: "700" },
  customerInfo: { marginBottom: Spacing.s },
  customerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.light.background,
    padding: 10,
    borderRadius: Radius.m,
  },
  customerName: { fontSize: 14, fontWeight: "600", color: Colors.light.text },
  customerInfoContainer: { marginLeft: Spacing.s, flex: 1 },
  customerPhone: {
    fontSize: 12,
    color: Colors.light.textSecondary,
    marginTop: 2,
  },
  addressBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: Spacing.s,
  },
  addressText: {
    fontSize: 13,
    color: Colors.light.textSecondary,
    marginLeft: 6,
    flex: 1,
    lineHeight: 18,
  },
  commentBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: Colors.light.background,
    borderRadius: Radius.m,
    padding: Spacing.sm,
    marginBottom: Spacing.m,
    gap: 6,
  },
  commentText: {
    flex: 1,
    fontSize: 13,
    color: Colors.light.text,
    lineHeight: 18,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.m,
    borderTopWidth: 1,
    borderTopColor: Colors.light.borderLight,
    paddingTop: Spacing.s,
  },
  price: { fontSize: 18, fontWeight: "800", color: Colors.light.text },
  date: { fontSize: 12, color: Colors.light.textLight },
  expandButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.s,
    marginBottom: Spacing.s,
    backgroundColor: Colors.light.primaryLight,
    borderRadius: Radius.m,
  },
  expandButtonText: {
    color: Colors.light.primary,
    fontSize: 13,
    fontWeight: "600",
    marginRight: 4,
  },
  itemsContainer: {
    backgroundColor: Colors.light.background,
    borderRadius: Radius.m,
    padding: Spacing.m,
    marginBottom: Spacing.m,
  },
  itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    alignItems: "flex-start",
  },
  itemName: {
    flex: 1,
    fontSize: 13,
    color: Colors.light.text,
    paddingRight: Spacing.m,
  },
  itemQty: { fontWeight: "700", color: Colors.light.textSecondary },
  itemPrice: { fontSize: 13, fontWeight: "700", color: Colors.light.text },
  actionButton: {
    paddingVertical: Spacing.sm,
    borderRadius: Radius.m,
    alignItems: "center",
  },
  actionButtonText: {
    color: Colors.light.white,
    fontSize: 14,
    fontWeight: "700",
  },
});
